#!/bin/bash
apt_install () {
    apt -y install $@
}

apt_update () {
    apt update
}

install_docker () {
    sudo apt remove docker docker-engine docker.io containerd runc

    apt_update
    apt_install ca-certificates curl gnupg lsb-release

    # add Docker repo
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    apt_update
    apt_install docker-ce docker-ce-cli containerd.io
}