#!/bin/bash
install_nginx () {
    apt update && apt -y install nginx
}

deploy_nginx_config () {
    echo $1 > /etc/nginx/sites-available/default
    service nginx restart
    source ~/.bashrc
}

deploy_nginx_http () {
    PORT=$1
    deploy_nginx_config "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    location /api/ {
        proxy_pass http://localhost:$PORT;
        proxy_http_version 1.1;
        }
    }"
}

deploy_nginx_https () {
    PORT=$1
    DOMAIN_NAME=$2
    
    deploy_nginx_config "server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name $DOMAIN_NAME;
        ssl_certificate /etc/letsencrypt/live/$DOMAIN_NAME/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/$DOMAIN_NAME/privkey.pem;

        location / {
            proxy_pass http://127.0.0.1:$PORT;
            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection \"Upgrade\";
        }
    }

    server {
        listen 80;
        listen [::]:80;

        server_name $DOMAIN_NAME;

        return 302 https://\$server_name\$request_uri;
    }"
}
