#!/bin/bash 
sudo apt install -y curl build-essential htop

source install_scripts/install_docker && install_docker
source install_scripts/nginx && install_nginx

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

printf '\n# adding deploy and update scripts to $PATH\nexport PATH=$PATH:'$SCRIPT_DIR'\n' >> ~/.bashrc && source ~/.bashrc

source update